name: markdownconverter
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.1.6
  http: any
  path_provider: ^0.4.1
  simple_permissions: ^0.1.6
  validator: ">=0.0.4 <0.1.0"
  date_format: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
